### ISSUE TITLE
A problem of slow data loading

### ISSUE THREAD

**Issue by codershenghai** [YijinHuang/pytorch-DR#1]
Hello! Do you have any problems with slow loading of images when using ImageFolder?  

I used your code of two_cates, and my problem here is that the picture preprocessing is very slow, resulting in a GPU utilization rate of 0 all the time. I suspect the reason is that the picture is too large. 

Please ask if you have this problem and how did you solve it, thank you!

**Comment by coderKyf** [comment]
Hello! Can I ask some questions?

Where can I get the 'o_O_large_79.pt'?
And how should I organize folders? Where should I put 'trainLabels.csv' ?

Thanks a lot!

**Comment by YijinHuang** [comment]
> Hello! Do you have any problems with slow loading of images when using ImageFolder?
> 
> I used your code of two_cates, and my problem here is that the picture preprocessing is very slow, resulting in a GPU utilization rate of 0 all the time. I suspect the reason is that the picture is too large.
> 
> Please ask if you have this problem and how did you solve it, thank you!

I'm sorry I was too late to reply. You should add num_works when you initialize dataloader to use multiple CPU to process images. I have added it in the newest version.
